version: '2'

services:

  api:
    container_name: express-app
    build: .
    ports:
      - 8080:3000
    depends_on:
      - mysql

  mysql:
    container_name: express-mysql
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ./initDB.sql:/docker-entrypoint-initdb.d/initDB.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: api
      MYSQL_USER: user
      MYSQL_PASSWORD: password