version: "3"
services:
  mysql:
    image: "mysql:latest"
    container_name: docker-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ticketdb
      MYSQL_ROOT_PASSWORD: root

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ticketapp
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      MYSQL_HOST: docker-mysql
      MYSQL_DATABASE: ticketdb
      MYSQL_ROOT_PASSWORD: root
