version: '3.1'
services:

  php:
    build:
      context: ./php
    volumes:
      - ../:/app
    working_dir: /app
    ports:
      - 8080:8000

  mysql:
    image: mysql
    ports:
      - 3360:3360
    volumes:
      - ../database/mysql_native_password_init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../database/dump.sql:/docker-entrypoint-initdb.d/refresh_data.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password