version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: streaming-mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_init/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: live-streaming

  live-streaming:
    image: live-streaming
    container_name: live-streaming
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: streaming-mysql
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: live-streaming
